### PR TITLE
Add most up to date mongodb functions

### PR DESCRIPTION
**Pull request by hermanator608**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

With the current mongo implementation, it is using some deprecated functions like `save`. I have added the latest functions like `insertOne`, `insertMany`, etc. but have left the deprecated functions to ensure it is non-breaking.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team. - I have not discussed this change
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality - No tests for mongodb module

### CODE REVIEW

**Comment by echoix** [comment]
I was wondering why this PR was closed before having a discussion or even merged into the node. I was eager to have these changes fixed. These 4 operations date back to the node driver 1.4 version, and the insertOne/insertMany have been the way to go since the 2.x release (2015), that the node-red-node-mongodb plugin uses since 16 Aug 2016. 
In the upcoming (in the next months) 4.0 release, the collection.save and collection.find methods are completely removed, while the insert, and update are still rewritten in the driver. So, this PR was useful to keep the plugin alive and functional in the future.

**Comment by hermanator608** [comment]
> I was wondering why this PR was closed before having a discussion or even merged into the node. I was eager to have these changes fixed. These 4 operations date back to the node driver 1.4 version, and the insertOne/insertMany have been the way to go since the 2.x release (2015), that the node-red-node-mongodb plugin uses since 16 Aug 2016.
> In the upcoming (in the next months) 4.0 release, the collection.save and collection.find methods are completely removed, while the insert, and update are still rewritten in the driver. So, this PR was useful to keep the plugin alive and functional in the future.
> 
> As of today, this plugin is the less broken MongoDB plugin for node-red, this spring, none were minimally functional with current MongoDB installations when I tried them all.

Hi @echoix, my team and I decided to move on from this package and implement our own. I ended up closing this PR as there was not a conversation or review and it was no longer needed for my team's needs.

**Comment by echoix** [comment]
And is the new package available for others, or your branch is the furthest you and your team got to improve MongoDB support in Node-RED? Since I'm working with Node-RED and MongoDB for a university final project, I know that I would be present for at least the next 8 months, but can't guaranty maintenance after that.

**Comment by echoix** [comment]
Hello @hermanator608, I would like to ask if you would allow me to start from the work started in this pull request to continue and improve the mongodb node later on. I think it was a good and much needed update to the node.

**Comment by hermanator608** [comment]
> And is the new package available for others, or your branch is the furthest you and your team got to improve MongoDB support in Node-RED? Since I'm working with Node-RED and MongoDB for a university final project, I know that I would be present for at least the next 8 months, but can't guaranty maintenance after that.

Hi @echoix, sorry for the slow response. My branch is the furthest we got. The new package we made is a private package within the Company that I work for.

> Hello @hermanator608, I would like to ask if you would allow me to start from the work started in this pull request to continue and improve the mongodb node later on. I think it was a good and much needed update to the node.

Yes you are more than welcome to steal my progress and open up your own PR against this Repo!

**Pull request closed without merging**
