### PR TITLE
PiSrf: Added decimal places option + stop bugfix + more keywords

### PR DESCRIPTION
**Pull request by JsBergbau**
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

Added option to output more decimal places. When no decimal places are configured output stays the same for full backward compatibility.

Fixed bug that on restart flows error "Error stopping node: Close timed out" occured. Also removed sudo, because no need to run code with root rights. On systems where you need password for sudo it wouldn't run then. 

Added Keywords for "HC-SR04" and "SR04", because this module is fully compatible with this node.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
functionality looks good - but is there any point is adding any more resolution than 1 dp ? Given that the datasheet for the SRF05 (which is supposed to be better than the 04) claims a resolution of 0.3 cm = 3.3 mm. Allowing any more just give a false impression of accuracy... (and indeed the actual accuracy seems to also varies with distance... so careful calibration would also be needed.  Some good testing done here - https://forum.arduino.cc/t/hc-sr04-tests-on-accuracy-precision-and-resolution-of-ultrasonic-measurement/236505

**Comment by JsBergbau** [comment]
Good point. More than one dp resolution makes no sense. 
I'll change to either 0 or 1 decimal places.

**Comment by JsBergbau** [comment]
Updated: Now only 0 or 1 decimal places are valid.

**Comment by dceejay** [comment]
Many thanks for this update

**Pull request merged**
