### PR TITLE
More Wemo update

### LINKED ISSUE #616: node-red-node-wemo error
## Which node are you reporting an issue on?

node-red-node-wemo v0.1.15

### What happens?

node-red crashes after running for about 24 hours with the following error:

[red] Uncaught Exception:
Error: connect ETIMEOUT 10.0.0.70:49153
at Object._errnoException (util.js:992:11)
at _exceptionWithHostPort (util.js:1014:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

### Please tell us about your environment:

- [ ] Node-RED version: v0.18.7
- [ ] node.js version: v8.11.3
- [ ] Platform/OS: Windows 7

### PR DESCRIPTION
**Pull request by hardillb**
Should fix #616 properly

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Added the missing timeout catch blocks

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Hi @hardillb - just refound this... should we resolve this now (I think you did fix it all your end didn't you ?

**Comment by hardillb** [comment]
Let me re-read it all in the morning and double check it. But yes those changes all just add more timeout checks.

**Comment by hardillb** [comment]
@dceejay OK, looks good, I've cleaned up the merge conflict.

**Comment by dceejay** [comment]
Thanks - did you publish it already ?

**Comment by hardillb** [comment]
No, didn't want to push to npm until it was merged

**Comment by dceejay** [comment]
ok - done it . Thanks

**Pull request merged**
