### PR TITLE
Email rework

### PR DESCRIPTION
**Pull request by nkolban**
This is my submission for email rework.  Now includes POP support, better IMAP support, attachments and more.

### CODE REVIEW

**Comment by dceejay** [comment]
thanks Neil,
Do you think you could squash those commits into a single commit - see eg https://davidwalsh.name/squash-commits-git - especially if your commit comments are errr.... somewhat vague :-)

**Comment by nkolban** [comment]
Howdy Dave,
I looked at the instructions but I'm afraid I'm not understanding them.  Git makes me nervous.  Would you be willing to spend the 10 minutes and get on a Skype call and screen share with me while we do this together interactively?  I am using the latest Eclipse on Windows as my Git development environment.  My skype is is "neil.kolban"

**Comment by dceejay** [comment]
node-red-gitbot please recheck cla

**Comment by knolleary** [comment]
node-red-gitbot: try again please... have fixed the typo in Neil's github username...

**Pull request merged**
