### PR TITLE
what3words: update support languages

### PR DESCRIPTION
**Pull request by utaani**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes
Added new support languages with  
https://docs.what3words.com/api/v3/#available-languages

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Have you checked this works with the v2.0 npm library we have ?

**Comment by utaani** [comment]
I checked this on Node-RED 0.20.8/node v10.16.3/npm 6.9.0.
image

**Comment by dceejay** [comment]
great - thanks.

**Comment by utaani** [comment]
I checked this on Node-RED 1.0.0-beta4/node v10.16.3/npm 6.9.0 too.

**Pull request merged**
