### PR TITLE
Physical-web: Added status (found, updated and lost) as msg.topic

### PR DESCRIPTION
**Pull request by natcl**
Physical-web: Added status (found, updated and lost) as msg.topic
Added the ability to filter duplicates.

### CODE REVIEW

**Comment by dceejay** [comment]
Nat, you have removed the existing topic field so that it can no longer be specified.... this will break anyone who happens to be using it today.

**Comment by natcl** [comment]
Hmm, how can we manage this ? Setting a static topic on this node is not very useful...

**Comment by dceejay** [comment]
you can add another property msg.status ? msg.action ?

**Comment by natcl** [comment]
yeah that's what I did in the beginning but didn't find it elegant since the topic isn't really useful...
Could we perhaps re-add the static topic and if it's define it will be sent and if it's blank the status will be sent instead ?

**Comment by dceejay** [comment]
yes - that is actually a great answer... make the topic placeholder (optional) and add some info to document the behaviour.

**Comment by natcl** [comment]
Cool will do, thanks !

**Comment by natcl** [comment]
Fixed !

**Pull request merged**
