### PR TITLE
Username and password server credentials.  

### PR DESCRIPTION
**Pull request by d4rr3ll**
Username and password credentials, specifically to allow connection to slack IRC.

### CODE REVIEW

**Comment by dceejay** [comment]
Hi thanks for this - have added some comments re the credential handling... 
We also need a CLA as per the contribution guidelines so we can accept the PR. Is that OK with you ?
(print, sign, photo, email is ok)

**Comment by d4rr3ll** [comment]
Thanks for the feedback, I'll make the changes and get the CLA sent in the next couple of days.

**Comment by d4rr3ll** [comment]
New changes committed.  @dceejay could you code review it if you get chance please?  I still need to get the paperwork sorted, will do it this weekend.

**Comment by dceejay** [comment]
Just need the cla and then we're good.
(Ideally we like the commits squashed into a single commit - but I'm not going to sweat it.)

**Comment by d4rr3ll** [comment]
OK, cool.  Noted about the squashed commits.  I sent the CLA over on Sunday.

**Comment by knolleary** [comment]
@node-red-gitbot : please recheck the CLA status - thanks! :+1:

**Pull request merged**
