### PR TITLE
Improve HTTP response handling and error reporting of emoncms node

### PR DESCRIPTION
**Pull request by borpin**
Following user comments, this update changes the way HTTP responses are handled and reported and improves error handling and reporting.

Version number bumped.

### CODE REVIEW

**Comment by knolleary** [comment]
Hi, as per our contribution guidelines we prefer to discuss enhancements before pull-requests arrive. You mention this is based on user comments - where are they? I don't recall seeing any discussion on this.

**Comment by borpin** [comment]
Ah, sorry.  Discussion here on the Open Energy Monitor forum.  It has been tested by these folks for a while. I'd always expected a few issues.

https://community.openenergymonitor.org/t/node-red-error-with-update/6171

Cheers

**Comment by dceejay** [comment]
Thanks for the fixes.

**Comment by borpin** [comment]
No Bother.

**Pull request merged**
