### PR TITLE
Adding No Auth support to social email out node

### PR DESCRIPTION
**Pull request by spawnrider**
Let email out node connect to SMTP without authentication.

### CODE REVIEW

**Comment by dceejay** [comment]
Thanks, looks like a good idea. Just needs the (admittedly basic) tests fixing up to now pass given new error messages.

**Comment by spawnrider** [comment]
@dceejay I added some test cases and more coverage to this node

**Comment by dceejay** [comment]
brilliant. thanks... - have you finished tweaking ? ok to merge ?

**Comment by spawnrider** [comment]
Yes. Thanks.

**Comment by dceejay** [comment]
Thanks for your contribution
now pushed to npm as 0.1.18

**Pull request merged**
