### PR TITLE
SQL error with HTTP request

### PR DESCRIPTION
**Pull request by paulRenault**
In the case the SQL node is in a flow with http in and out, the flow end
in case of error but the http client is waiting for an answer. So we
must not endded the flow but send back the error.

### CODE REVIEW

**Comment by knolleary** [comment]
Hi,

you'll see in the code you removed there was a call to `node.error(err,msg);`.

That error can be caught by a `Catch` node on the same tab as the sql node, and the message passed to that node. That allows you to create an error-handling flow that will respond to the HTTP request appropriately.

No changes are needed to the node itself.

Nick

**Comment by paulRenault** [comment]
Hi,

The HTTP in and HTTP out need to be in the same flow to share the headers ?
Am I wrong ?

Paul

**Comment by knolleary** [comment]
The key thing is the message object that gets passed through. The Catch node is given the message from the sql node so it contains everything needed to respond to the originating http request.

**Comment by paulRenault** [comment]
OK

Thanks

**Pull request closed without merging**
