### PR TITLE
Move English help to en-US directory

### PR DESCRIPTION
**Pull request by kazuhitoyokoi**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
Based on [the document about internationalization](https://nodered.org/docs/creating-nodes/i18n), I moved English help text to `en-US` directory.
 
## Checklist
- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Are we expecting new Ja translations to go along with these changes ? Shall I leave the PR open for them to be added ?

**Comment by kazuhitoyokoi** [comment]
@dceejay Thank you for your consideration. There is no need to open this pull request because it is just pull request to move English messages under the en-US directory. I think that this fix was needed when we created Japanese HTML files. When I find the update of the original English text, I will add Japanese translations on demand.

**Comment by dceejay** [comment]
Hi - just checking - this is OK to merge isn't it ?
the Ja translations are already in place.

**Comment by kazuhitoyokoi** [comment]
@dceejay Yes. Could you merge it?

**Comment by kazuhitoyokoi** [comment]
@dceejay Thank you!

**Pull request merged**
