### PR TITLE
added i18n help files

### PR DESCRIPTION
**Pull request by heikokue**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes
separation of help-parts to separate en-US locales html files.
no content changes.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
It's gong to take a while to go through them all before we can merge them - it would have been easier if a) they had been discussed on the forum first and b) were in smaller chunks of a few nodes at a time.

**Comment by heikokue** [comment]
Hello! Oh, sorry for my endeavor to improve Node-RED. We have current Corona lockdown in Germany and I tried to spent my time for are meaningful job. Up to now I spent over 50 hours to improve the german UI.

Regarding a) The plan to improve the DE translation is already discussed in Slack channel #18n-de and in the Forum https://discourse.nodered.org/t/german-translation-anyone-interested/38209/4. The feedback is quite small...

Regarding b) This PR has **no** content change. Only the help text parts in the of the node's main html files are moved into separated html files in locales/en-US folder.
This shall be the 1st step, before as 2nd step the DE translations shall be added in locales/de folder in separate PRs.

How to continue?
Shall I split this PR node for node?

**Comment by knolleary** [comment]
We so appreciate your effort, it is just a case of how you chose to do it.

I don't remember you mentioning a plan to split up all the nodes help files in both this and the web-nodes repos. Of you had mentioned it, we would have asked you to do it a few at a time and not in one big PR.

No point splitting it up now - it's just going to have to wait until we've checked all the changes.

**Comment by heikokue** [comment]
As understand, a split is necessary to have separate locales and to create translations, or not?
As I started with the core (main repo), all locales files are already created.
But some popular nodes of node-red-nodes and node-red-web-nodes are not prepared for i18n.
I also understand your situation to receive PRs in a suitable size.
So no problem, it's OK for me, If you want me to split the PRs in smaller pieces, I will do it.
One PR for each node locales split?

**Comment by heikokue** [comment]
I just created #769 as smaller chunk of this PR.
Is #769 OK for you?
If yes, I will continue to create PRs for each single node and close this PR.

**Comment by dceejay** [comment]
Hi - yes - much more digestible :-)
The key ones (for core) are rbe, sentiment, and tail
Then our Pi image also adds random, gpio, ping, serialport, smooth
so those would be priority ones to add first IMHO
Then often used ones are email, xmpp, sqlite, mysql, daemon, (datagenerator), base64, msgpack
Then any others.
If you do decide to do one PR per - then by all means also add the de translation file also (for those that you have)

**Comment by heikokue** [comment]
OK, thanks for feedback.
I will split it in smaller chunks, no problem!

**Comment by dceejay** [comment]
Having now had a chance to review this - I'm happy to merge this as-is, as indeed as you point out this is just the mechanical moving of the files out to correct locations for i18n. We can then add the translations later and republish.

**Comment by heikokue** [comment]
> 
> 
> Having now had a chance to review this - I'm happy to merge this as-is, as indeed as you point out this is just the mechanical moving of the files out to correct locations for i18n. We can then add the translations later and republish.

This was exact the idea/plan of this PR.
Sorry for my englisch and when it's not completely clear, what I try to explain.
Englisch is your domain, but German is mine.
And furthermore I'm a experienced IT developer and hope, my DE changes are more improvements than degradations ;-)

**Pull request merged**
