### PR TITLE
Updated pushbullet node with all push types, added new "pushbullet in" t...

### PR DESCRIPTION
**Pull request by dsundberg**
...hat emits pushes. Added unit tests.

### CODE REVIEW

**Comment by dsundberg** [comment]
Will migrate old version of pushbullet.

test flow:
```
[{"id":"cca30d70.335cf","type":"pushbullet-config","name":""},{"id":"4fb39184.b04c7","type":"pushbullet in","config":"cca30d70.335cf","name":"","x":100,"y":378,"z":"5194a0bd.ae6b6","wires":[["1ec65cbe.e139a3","95f0f0a5.6a0f1","8e76cf53.71893"]]},{"id":"1ec65cbe.e139a3","type":"function","name":"pretty print","func":"try {\n\treturn {payload: JSON.stringify(msg, null, 2)};\n}\ncatch(err) {\n\treturn {payload: msg};\n}","outputs":1,"x":266,"y":378,"z":"5194a0bd.ae6b6","wires":[["ba224e84.45ddb"]]},{"id":"95f0f0a5.6a0f1","type":"debug","name":"","active":true,"console":"false","complete":"false","x":423,"y":418,"z":"5194a0bd.ae6b6","wires":[]},{"id":"ba224e84.45ddb","type":"file","name":"","filename":"pushbullet_log.txt","appendNewline":true,"overwriteFile":"false","x":438,"y":378,"z":"5194a0bd.ae6b6","wires":[]},{"id":"4c8cdbee.b37324","type":"function","name":"generator","func":"msg.pushtype = msg.topic;\ndelete msg.topic;\nswitch(msg.pushtype) {\n\tcase 'note':\n\t\tmsg.topic = 'note test';\n\t\tbreak;\n\tcase 'link':\n\t\tmsg.topic = 'link test';\n\t\tmsg.message = 'you should really visit this!';\n\t\tbreak;\n\tcase 'list':\n\t\tmsg.topic = 'list test';\n\t\tbreak;\n\tcase 'address':\n\t\tmsg.topic = 'address test';\n\t\tbreak;\n\tcase 'file':\n\t\tmsg.topic = 'file test message';\n\t\tbreak;\n\tcase 'delete':\n\tcase 'updatelist':\n\tcase 'dismissal':\n\t\tbreak;\n\tdefault:\n\t\treturn null;\n}\nreturn msg;","outputs":1,"x":488,"y":77,"z":"5194a0bd.ae6b6","wires":[["5f5d40e8.a0a2c"]]},{"id":"5f5d40e8.a0a2c","type":"pushbullet","config":"cca30d70.335cf","pushtype":"","title":"","chan":"","name":"","x":627,"y":77,"z":"5194a0bd.ae6b6","wires":[]},{"id":"7d059b38.82fa64","type":"inject","name":"","topic":"note","payload":"this is a note","payloadType":"string","repeat":"","crontab":"","once":false,"x":122,"y":162,"z":"5194a0bd.ae6b6","wires":[["4c8cdbee.b37324"]]},{"id":"b88162ac.477ea","type":"inject","name":"","topic":"link","payload":"http://localhost:1880","payloadType":"string","repeat":"","crontab":"","once":false,"x":141,"y":66,"z":"5194a0bd.ae6b6","wires":[["4c8cdbee.b37324"]]},{"id":"9abd64e0.654298","type":"inject","name":"","topic":"address","payload":"IBM, Winchester, UK","payloadType":"string","repeat":"","crontab":"","once":false,"x":157.5,"y":34,"z":"5194a0bd.ae6b6","wires":[["4c8cdbee.b37324"]]},{"id":"5df89789.a20768","type":"inject","name":"","topic":"file","payload":"pushbullet_test.txt","payloadType":"string","repeat":"","crontab":"","once":false,"x":134,"y":130,"z":"5194a0bd.ae6b6","wires":[["4c8cdbee.b37324"]]},{"id":"5b227018.a4dd9","type":"inject","name":"","topic":"list","payload":"[\"a\", \"list item 2\", \"last one\"]","payloadType":"string","repeat":"","crontab":"","once":false,"x":91,"y":98,"z":"5194a0bd.ae6b6","wires":[["4c8cdbee.b37324"]]},{"id":"8e76cf53.71893","type":"function","name":"Cache","func":"if(msg.data) {\n\tcontext.last = msg.data;\n}\nelse if(context.last) {\n\tmsg.data = context.last;\n\treturn msg;\n}\n\nreturn null;\n\n","outputs":1,"x":318,"y":254,"z":"5194a0bd.ae6b6","wires":[["4c8cdbee.b37324"]]},{"id":"93c6f846.6c3908","type":"inject","name":"","topic":"delete","payload":"","payloadType":"string","repeat":"","crontab":"","once":false,"x":92,"y":224,"z":"5194a0bd.ae6b6","wires":[["8e76cf53.71893"]]},{"id":"ca45a9a9.35ba58","type":"inject","name":"","topic":"updatelist","payload":"[{\"checked\":true, \"text\":\"hello\"}]","payloadType":"string","repeat":"","crontab":"","once":false,"x":97,"y":256,"z":"5194a0bd.ae6b6","wires":[["8e76cf53.71893"]]},{"id":"f04d325e.0fb2d","type":"inject","name":"","topic":"dismissal","payload":"","payloadType":"string","repeat":"","crontab":"","once":false,"x":97,"y":288,"z":"5194a0bd.ae6b6","wires":[["8e76cf53.71893"]]},{"id":"4385d997.bc7a28","type":"inject","name":"Create file","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":536,"y":196,"z":"5194a0bd.ae6b6","wires":[["6efd3d9e.9102c4"]]},{"id":"6efd3d9e.9102c4","type":"file","name":"","filename":"pushbullet_test.txt","appendNewline":true,"overwriteFile":"true","x":703,"y":196,"z":"5194a0bd.ae6b6","wires":[]},{"id":"f149a08c.0eb66","type":"inject","name":"Delete file","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":535,"y":236,"z":"5194a0bd.ae6b6","wires":[["c1e6bc2e.3e194"]]},{"id":"c1e6bc2e.3e194","type":"file","name":"","filename":"pushbullet_test.txt","appendNewline":true,"overwriteFile":"delete","x":723,"y":236,"z":"5194a0bd.ae6b6","wires":[]}]
```

**Comment by dceejay** [comment]
Hi Daniel
just tried this new version - while the extra function looks really good - it didn't migrate my previous API key settings so all my original flows were broken. I guess this is because the API key was in the node and is now part of the config node.

**Comment by dsundberg** [comment]
Hi Dave,

Obviously some bad ui testing on my part. Made sure the credentials are
"migrated" when you load an old config, this works when loading an old flow
and pushes get through for me. BUT you also get a red warning triangle on
the node showing that the config is missing (although it is there behind
the scenes). And once the node is edited the migrated information is lost
unless of course the information is added manually.

Will look into this tomorrow and figure out a way to solve it. I'm
wondering if I could generate the missing config node automagically on the
first edit so all that needs to be done is to open the edit dialog and
click ok, then deploy? Another option is to make the node fine with having
old credentials, this would not allow for an input node to use the same
credentials though since there would be no config node.

If there are any other suggestions on how to handle this I'm all ears.

**Comment by dceejay** [comment]
Ah  right - yes it was actually working but I thought it wasn't due to the triangles.

**Comment by dceejay** [comment]
Maybe use oneditprepare to add "Migrated" to select and be selectef. So triangle appears on first use. But open will show what is happening and close will allow to carry on without further warning.

**Comment by dsundberg** [comment]
This should be better, node has status migrated but no "error", if node is edited the "upgrade" will take place and on next deploy it is a compliant v2 of the pushbullet node.

**Comment by dceejay** [comment]
Hi - much better :-)... So now... if i migrate something and restart - I never get anything other than all or set from msg.deviceid for the Device to send to...  Is this an effect of not really setting up the credentials properly ? If unavoidable can we add a Tip: to the edit panel ?

(Tiny nit - need to update the copyright date to be 2013,2015)

**Comment by dsundberg** [comment]
I did something bad, fixed it with a --amend and did a force push 5 min
after, you might have gotten the bad one. Think if you test the patch again
it will work as expected. Will sort the copyright date. Can squash this
when its ready.

**Comment by dceejay** [comment]
Hi, that now seems to be worse - now a straight migrate - ie - just restart node-red - and the original flow doesn't work...  and still no other devices in the list...

(PS the copyright needs to be    ... 2013,2015  - both dates - original and last major update)

**Comment by dsundberg** [comment]
Hmm, need to setup some proper tests tomorrow and sort this. In the meantime I'd recommend setting up an input node and then enable "universal copy&paste" in your PB apps, fun to log copy behavior, or turn off lights by copying "off" or other magic keywords  :)

**Comment by dceejay** [comment]
Yeah - am liking the new functionality.

**Comment by dceejay** [comment]
Ok - have recopied everything carefully - and it does seem to work - not sure what I missed last time. Only thing I would say (apart from the copyright date) is that warning message says
     Settings migrated from previous version of Pushbullet Node, please re-deploy to save settings!
just deploying isn't enough - you need to open and close the edit window (which then requires a redeploy) - so maybe ..... please edit node to update settings.   ?

**Comment by dceejay** [comment]
Could the input node also only "listen" to one deviceid. ?

**Comment by dsundberg** [comment]
All good points! 

Warning message and (c) fixed.

Looking into device name in the title, only the deviceid is kept at the moment and the rest queried from PB when opening the edit dialog, might be a good idea to cache the device names anyways. Or would it be any good to display the device id, not that user friendly?

msg.data is set by the input node and that will contain msg.data.iden, so to dismiss a push you need to capture it from the input node then send it to a output node with push type dismissal. Updated node doc somewhat to clarify.

Input connection have been rock solid for me, is it only the status that goes disconnected or does the input node stop working til next restart?

Might make sense to filter on device in the node since the ids a quite tricky to get hold of if you want to do filtering in a function node. What about push type filtering?

**Comment by dsundberg** [comment]
Added a device filter to the input node, allows multiple selection as well. 

As for the device name in the node label: could either store the name in the node config which would be somewhat redundant since deviceid is the actual identifier, or do a name query to the backend node on the label() call which when resolved sets the node.dirty = true and asks for a redraw.

**Comment by dsundberg** [comment]
Tried the second route, device name set as label if any device is set. Priority is name || devicename || title || "pushbullet", think name should always override, not sure about title.

**Comment by dceejay** [comment]
yeah me neither (re title) - but yes priority order correct. I'm happy for you to squash it if you like.

**Comment by dsundberg** [comment]
Found and fixed some edge cases and added some tests. Final questions, for
the filtering on the input node: when a device is selected should a push
going to all devices pass as well?

On Tue, Feb 3, 2015 at 10:48 PM, Dave Conway-Jones <notifications@github.com

**Comment by dceejay** [comment]
Yes... It is part of the all set in my book .

**Comment by dsundberg** [comment]
Found another edge case... what should happen if you "migrate" a non/half
configured pushbullet node?

On Thu, Feb 5, 2015 at 11:41 PM, Dave Conway-Jones <notifications@github.com

**Comment by dsundberg** [comment]
Working on sorting partial migrate, if no credentials found at all the node will just be an un-configured "new" pushbullet node.

**Comment by dceejay** [comment]
Hi, yes good plan - makes sense. 
Any chance we can get the commits squashed down fairly quick. We are about to push out v0.10 and need to do some other tweaks to nodes as part of that - so want to get your big change in first.
Thanks

**Comment by dsundberg** [comment]
Sure, will get it working tonight I hope... already squashed all but this last fix

**Comment by dsundberg** [comment]
Partial migration fixed. Had to bring the warning back since the custom validation had a hard time with partial migration. Migrated node will work as before but show "Migrated" status AND the warning symbol for a non validated node, both will disappear once edited and re-deployed.

**Comment by dceejay** [comment]
Many thanks for this - I know it's been a bit of a pain, but I think the extra function now is great.

**Comment by dsundberg** [comment]
No pain no gain :) While a sorta' working fork would have solved my needs this was way more fun. Part of the gain is to keep my brain working while on a loong parental leave. Thanks for all your input. If any issues were to show themselves I'm happy to take a look.

**Comment by dceejay** [comment]
You do look like you have both hands full there ! Good luck with that !

**Comment by dsundberg** [comment]
Thanks, need a bit of luck with the "dynamic duo" ;)

**Pull request merged**
