### PR TITLE
Define raw_input() in Python 3

### PR DESCRIPTION
**Pull request by cclauss**
* __raw_input()__ was removed in Python 3 in favor of __input()__
* __SystemError__ was removed in Python 3 in favor of __Exception__
* __print()__ is a function in Python 3
* Fix up __time.sleep()__ to match the import

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Excellent. Thanks. Will look properly and merge when back from vacation

**Comment by dceejay** [comment]
Is this all backwards compatible with python 2 as that is still the default install for Pi for the foreseeable future

**Comment by cclauss** [comment]
It is compatible with both but Python 2 EOLs in 500 days... https://pythonclock.org

**Comment by cclauss** [comment]
Whatup with __Error: Cannot find module 'multilang-sentiment'__?

**Comment by dceejay** [comment]
500 days is over a year away! We’ll have several versions of nodejs to deal with before then :-)

Don’t worry about the sentiment error. Will fix that when I get back also. Ignore it.

**Comment by cclauss** [comment]
#474 incorporates all of these changes and adds flake8 tests to Travis CI on both Python 2 and Python 3.

**Pull request merged**
