### PR TITLE
Improve restart upon timeout (#338)

### PR DESCRIPTION
**Pull request by denisfrench**
This might still need some work; I'm very rarely getting a "local variable 'stop' referenced before assignment" exception, but can't see where it is occurring.

It's happening so infrequently I can't effectively troubleshoot. It doesn't seem to be when restart() is invoked (there is none of the associated print() output to the terminal). Any assistance appreciated.

### CODE REVIEW

**Comment by denisfrench** [comment]
Work-in-progress really; it seemed more reliable but I was stuck troubleshooting that occaisional error.

I've since found some inspiration here; https://electrosome.com/hc-sr04-ultrasonic-sensor-raspberry-pi/#comment-1969107914 and am working on implementing interrupts rather than polling the ECHO pin.

I'm hopeful this will significantly improve reliability. It has been my subjective impression that the whole flow was less responsive (eg missing MQTT inputs) when the nrsrf node was enabled, perhaps due to the CPU load of polling the input.

I'll get it working better and resubmit...

**Comment by denisfrench** [comment]
I've converted the Measure() function to detect interrupts instead of polling the state of the ECHO pin.

This appears to have been so successful at avoiding missing the echo pulse that I have not seen the sensor timeout invoking the restart() function at all.

CPU load reduction is barely noticeable (maybe 1% on an RPi Zero W); perhaps this wasn't a problem in the first place. Otherwise this is now working fine.

**Comment by dceejay** [comment]
ok - so good to merge, or any outstanding wrinkles ?

**Comment by denisfrench** [comment]
Yep; seems fine at this end.

**Pull request merged**
