### PR TITLE
Add IOT2050 board into mraa Intel nodes

### PR DESCRIPTION
**Pull request by fr0st61te**
Porting from IOT2050 to mraa Intel nodes:

1. add IOT2050 board into PWM, AIN, DOUT
2. clean up on close for PWM, AIN, DOUT
3. add LED into GPIO category

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@fr0st61te thanks for this. Did you sign the EasyCLA mentioned above ↑ ?

**Comment by jan-kiszka** [comment]
We likely need to run this through our corporate process first, clarifying ATM.

**Comment by fr0st61te** [comment]
> Any joy with your signoff process ?

Now, it's done :)

**Comment by dceejay** [comment]
Many thanks !

**Pull request merged**
