### PR TITLE
fix pool on acquire event cause MaxListenersExceededWarning

### PR DESCRIPTION
**Pull request by saknarak**
- [ X ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### before
every query need to register pool on acquire event to specify `queryFormat` based on payload type
will cause `MaxListenersExceededWarning`

### after
from https://www.npmjs.com/package/mysql#pooling-connections

`pool.query` is a shortcut for `pool.getConnection()` -> `connection.query()` -> `connection.release()`

so use `pool.getConnection` and then
set `queryFormat` before `query` method be called

## Checklist

- [X] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [X] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Merged to test branch for using mysql2 library for wider testing... will release beta node later

**Comment by dceejay** [comment]
@saknarak Published to npm as node-red-node-mysql@next for testing
will need manual install    `cd ~/.node-red && npm install node-red-node-mysql@next`
then restart

**Comment by saknarak** [comment]
I just test with both `array` and `object` payloads with high volume messages.
Everything work as expect, no more  `MaxListenersExceededWarning` warning

**Comment by dceejay** [comment]
Great, thanks for the PR and the feedback.
I would like some others to do some more testing on it first before I release it more widely as it is also moved to the mysql2 lib as that fixes the "old" auth problem with mysql, and seems more maintained, but does have a couple of minor differences. So there will be a short delay before it gets made into @latest.

**Pull request merged**
