### PR TITLE
Add support for pushover sound selection.

### PR DESCRIPTION
**Pull request by Shirk**
Pushover supports a list of [notification sounds](https://pushover.net/api#sounds) to select from when pushing a notification.

This PR extends `PushoverNode` to honor the optional `msg.sound` field for this purpose.
If `msg.sound` is specified and contains a string it will be passed as the sound parameter.
If it's not set or not a valid string the same behavior as before is used.

### CODE REVIEW

**Comment by bigmonkeyboy** [comment]
Thanks - have seen CLA discussion on mailing list.

As there is a limited set... - do you also want to add a select box to the config dialog to allow user to set manually also ? default should be - nothing selected... and if nothing selected then msg.sound can override.

**Comment by Shirk** [comment]
Good idea, I'll update the PR :smile:

**Comment by dceejay** [comment]
node-red-gitbot: check cla status

**Comment by Shirk** [comment]
node-red-gitbot: check cla status

**Comment by knolleary** [comment]
let's try that again - node-red-gitbot, do your thing.

**Pull request merged**
