### PR TITLE
improved en-US help of rbe node

### PR DESCRIPTION
**Pull request by heikokue**
- [?] Bugfix (non-breaking change which fixes an issue)
- [?] New feature (non-breaking change which adds functionality)

## Proposed changes
- Added "It can also block unless, or ignore if the value changes by a specified amount." to pop-up help
- Both Deadband **and Narrowband** also supports % ...
- link to Deadband wikipedia
- small html source formats

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by heikokue** [comment]
PS. I'm just working on the DE help. You can wait with the bump until I finished with it.

**Comment by dceejay** [comment]
OK - let us know when you are ready.

**Comment by heikokue** [comment]
Can you please review it in advance? I think the english help was not completely clear and I like to use this as base for the german translation, if you accepted this PR.

**Comment by dceejay** [comment]
looks fine to me.

**Pull request closed without merging**
