### PR TITLE
Updates to match API changes

### PR DESCRIPTION
**Pull request by borpin**
Update to the node to match the server API changes. An attempt has been made to leave a legacy path for existing installations that may have not updated the server side.

Allow ISO format dates.

Add output of status information.

### CODE REVIEW

**Comment by dceejay** [comment]
Several thoughts....
Not the end of the world but as flagged over in the Issue #391 old versions default to a blank option...
image

This can be caught by using an oneditprepare function to set it if it's undefined.
Also we usually leave the Name field as the last in the list so move the datatype up.

You have also added an output pin to the output node. We prefer nodes that "end" a flow to not have this. You can use node.status to add an indicator (and text), or node.error to throw an error - these can be caught by the status node or catch node respectively if required.

Also the info doesn't explain the difference between basic and full json options...

**Comment by borpin** [comment]
Hi Thanks for the feedback. Seems I managed to get the PR part right!

1. Not sure how to implement a 'oneditprepare'; nothing immediately was thrown up by a google.
2. Output - fair enough - it helped me debug what I was doing. I understand the status, but not sure on how to implement the use of node,error.

The JSON is a bit of a peculiarity for emoncms.  Early implementations of the API had a non compliant JSON like data format that is still part of the API for legacy purposes.  The 3 types of input would be understood by someone trying to interface to the server so I think the explanation is sufficient.

Do you have some sample implementations for issues 1 & 2 that I can use?  Coding in general isn't new to me; Javascript / Node-red is.

**Comment by dceejay** [comment]
Hi
re 1 - look at for example - https://github.com/node-red/node-red/blob/master/nodes/core/storage/50-file.html#L167 - 8 etc
re 2 - node.error syntax is usually node.error("some error message for the sidebar",msg)   where msg is the incoming msg that caused the error.

**Comment by borpin** [comment]
Sorry, bit stuck on the oneditprepare.  Tried this code but the syntax is obviously wrong as the flow does not load.

`        oneditprepare: function() {
            if (this.datatype === undefined) {
                $("#node-input-datatype").val() = "legacy";
            }
        }
`
I'm unfamiliar with the '$' syntax and what it is actually doing. It is clear the # tells it what id to be looking at.  Trying to find a suitable reference also proved challenging.

**Comment by dceejay** [comment]
it's standard jQuery - so      .val("legacy")

**Comment by dceejay** [comment]
Just update this one

**Comment by borpin** [comment]
Sorry, can't see an obvious way to do that :(

**Comment by borpin** [comment]
Ok, think I have done that more by luck than anything else.

**Comment by borpin** [comment]
Updated README to cover new functionality.

**Pull request merged**
