### PR TITLE
temporary solution for direct messages

### PR DESCRIPTION
**Pull request by eRudy**
Added a detection of the pattern "D < user > < message >" in order to use the specific function of the twitter-ng library to send direct messages (newDirectMessage).

Sadly it's only a temporary fix, since the API will be deprecated in June 19, 2018 (https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration)

### CODE REVIEW

**Comment by eRudy** [comment]
I corrected the code, I don't know how to solve the issue ? close this request and open a new one after a new commit ?

**Comment by knolleary** [comment]
Thanks @eRudy.

If you push another commit, the PR will pick it up automatically.

However, if this is still using the deprecated API, then it doesn't buy us much. The required work is to move to the new api once and for all.

**Comment by eRudy** [comment]
I understand, but should not the correction done in the twitter-ng library used by node-red ?

**Comment by dceejay** [comment]
Thanks - As noted this is a short term fix... what we really need is to move to the new API

**Pull request merged**
