### PR TITLE
Smtp server

### PR DESCRIPTION
**Pull request by daviddhauwe**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

Node-red-node-email more options for e-mail mta: make the smtp server more 'production ready'.
I've added the possibility to add TLS encryption or to use the Start TLS command. By default self-signed certificates are used, but it is possible to add your own certificates.
Authentication can be done with PLAIN or LOGIN and users can be defined.
Additional 'expert' options from <a href="https://nodemailer.com/extras/smtp-server/" target="_new">nodemailer SMTP server</a> can be made in as JSON.
The extra configurations have defaults so the node behaves exactly the same as before the change.
I did not add or change unit tests so it can be verified there are no breaking changes.

image

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Excellent - thanks

**Comment by dceejay** [comment]
My only thoughts are....
1) when you select secure connection should the default port change to 465 ? (rather than remain 25 ?)
2) should all the extra options be hidden until you select secure connection ( as they may just confuse anyone who doesn't need them )

**Comment by daviddhauwe** [comment]
@dceejay 
1. The default port is 1025 (I guess because on linux lower ports require root rights) - so changing this to 465 when selecting secure connection might be problematic too. In the e-mail node it is also not done. In the help, there is a note explaining ports and security. I propose to add a note like this: 
**In most cases when using port 465, check Secure connection. For port 587 or 25 keep it disabled, use Start TLS instead.**
2. I will do that: certificate and private key fields will be visible when secure connection or start tls is checked. When authenticate uses is checked, the users input will be visible.

**Comment by dceejay** [comment]
1) true - yes please to note.
2) great - thanks - will be much neater.

**Comment by coderofsalvation** [comment]
awesome work. But is there an easy way to change the json-textarea to a javascript-textarea?
I need to add an `inConnect` handler to block some spambots (but can't because the jsonvalidation fails)

**Comment by dceejay** [comment]
No - we do not support JS as a typed input.

**Comment by coderofsalvation** [comment]
ok thanks for getting back to me, I'll have to monkeypatch it another way then.

**Comment by dceejay** [comment]
Hello ! and sorry - but opening up a general JS type input is just too fraught with possibilities for code injection.

**Comment by coderofsalvation** [comment]
wait..are you now reasoning purely from a theoretical problem standpoint?
I just wanted to know if there's a JS type input supported in the ui-codebase for nodes.
To be clear: I don't really care about merging such patch upstream (I won't).
I just noticed there's a 'function'-node which allows JS but I noticed the textarea was declared in a totally different way than the json-textarea in this node.
If there's a quick workaround for this let me know.
Again, it is not my intention to steer the future-direction of this node, just to fix a local issue.

**Comment by dceejay** [comment]
Well currently there is no input msg to that node... and once you are into hacking the code at that level you may as well just code in the callback directly :-)

**Pull request merged**
