### PR TITLE
Add SNMPv3 to node-red-node-snmp

### PR DESCRIPTION
**Pull request by Steve-Mcl**
Closes #705

This PR is based on #705 & addresses the concerns raised on the PR Review.
#705 is an abandoned PR for adding v3 support.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

* Update to latest SNMP lib
* Add support for SNMPv3
  * v3 username, authkey and privkey are moved to credentials
* Improve DRY by encapsulating repeated code in helper function
* Code tidy
  * replacing all vars to const+let
  * auto formatted for consistent spacing

### Notes
* Since a varbind error in SNMP.get node still sends a message, I added a property `_error` to each result that fails.
Ideally, the `get` node would NOT output a msg if a varbind has an error but this would change the behaviour.
* A future version of this node should move the majority of the repeated HTML to a config node. This would also fix the frustration of having to fill out the credentials every time.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
@knolleary @dceejay 

I have signed the CLA - not sure why this is not picking up?

**Comment by hardillb** [comment]
@Steve-Mcl It's not complain about you, it complaining about an update from @ASH3xC0d3

**Comment by Steve-Mcl** [comment]
@dceejay Dave, are you OK to review this or should I request someone else? or are you happy for me to merge? 
Thanks.

**Comment by dceejay** [comment]
Hi @Steve-Mcl 
yes - I don't have anything (that I know of) to test v3 against... but the menus / options seem fine to me.

**Comment by Steve-Mcl** [comment]
@dceejay I have tested against a physical device and snmpd on Ubuntu. 

Had to do a fair bit debugging to get past this issue - 
markabrahams/node-net-snmp#202 (kindly fixed by the guys over at net-snmp) - so it has had a fair good looking at (from me)

Can we agree since it is a new feature and the original SNMP v1/2 are pretty much unchanged that we can merge it and see if anyone raises any issue?

**Comment by dceejay** [comment]
I'm fine with that.
Also maybe version bump to 1.0.0 - so future minor changes get pulled in ok if folk specify ^.

**Comment by Steve-Mcl** [comment]
Cool. 
I'll bump and merge tomorrow. 

Will let you know so that it can be published.

**Comment by Steve-Mcl** [comment]
@dceejay could you release to NPM please?

**Pull request merged**
