### PR TITLE
Add topic event support for IRC node

### PR DESCRIPTION
**Pull request by endreszabo**
This commit adds support for IRC channel topic change events.

### CODE REVIEW

**Comment by knolleary** [comment]
HI, thanks for raising this. Please have a read of our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md). In this instance, this sounds like a useful feature to have, so no need to discuss on mailing list first. But we do need a CLA in place before we can accept any code from you. Let me know if you want to proceed.

Thanks, Nick

**Comment by endreszabo** [comment]
Hey Nick,

Thanks for the heads up. To be honest I'm not a pro dev, and this is the very first time I face this CLA thing. :) Sorry for disturbing you with such a newbie question, but I don't know how should I submit my printed-signed-scanned CLA pdf to have it on record.

Any help would be appreciated, thank you.

**Comment by knolleary** [comment]
Hi, no problem. You just have to email it to me - the details are in the CLA itself.

**Comment by dceejay** [comment]
Hi @endreszabo - your code looks fine to me - so up to you if you want to do the CLA. 
If you don't then as it's just a few lines I can hand edit this end if you like... but then you don't get the "credit" :-)

**Comment by knolleary** [comment]
Forgot to say, we have the cla, just haven't had a chance to process it.
Will do tonight.

**Comment by knolleary** [comment]
node-red-gitbot: please recheck the cla status

**Pull request merged**
