### PR TITLE
add strings for cluster support

### PR DESCRIPTION
**Pull request by ibmrcruicks**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by hardillb** [comment]
It will be easier to review all the changes for adding cluster support in one pull request, rather than spread across lots of different ones

**Comment by ibmrcruicks** [comment]
I know, Ben -- my screw up - would it be easier if I updated in my fork, and then re-issue as a single PR? (original plan but found myself editing the mater repo instead late last night)

**Comment by hardillb** [comment]
Yes please, you should be able to just merge all the branches on your fork into a single branch and then issue a single pull request from that branch.

**Comment by hardillb** [comment]
Please close the other pull requests when you are read.

**Pull request closed without merging**
